version: '3.8'

services:
  postgresdb:
    image: postgres
    ports:
      - '5432:5432'
    container_name: postgres-db
    environment:
      - POSTGRES_DB=gept_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ="America/Fortaleza"
    volumes:
      - ./db/:/data/db
