name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Pull Docker Image
        run: sudo docker pull 301008/gept-backend:latest

      - name: Delete Old Docker Container
        run: sudo docker rm -f gept-backend-api || true

      - name: Run Docker Container
        run: sudo docker run -d -p 4000:4000 --name gept-backend-api 301008/gept-backend
